server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo,classpath:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info
