CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS todo;

CREATE USER IF NOT EXISTS 'mickey'@'%' IDENTIFIED BY 'letmein';
GRANT ALL PRIVILEGES ON user_db.* TO 'mickey'@'%';
GRANT ALL PRIVILEGES ON todo.* TO 'mickey'@'%';
FLUSH PRIVILEGES;
