#!/bin/bash
set -euo pipefail

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS todo;

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON user_db.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON todo.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
